<?php
if ( ! defined( 'ABSPATH' ) ) {
    exit; // Exit if accessed directly
}

if ( ! class_exists( 'WC_Session_Handler' ) ) {
	return; // Fallback to default if something is wrong
}

class WC_Session_Handler_Extended extends WC_Session_Handler {
    	/**
	 * Setup cookie and customer ID.
	 *
	 * @since 3.6.0
	 */
	public function init_session_cookie() {
		$cookie = $this->get_session_cookie();

		if ( $cookie ) {
			// Customer ID will be an MD5 hash id this is a guest session.
			$this->_customer_id        = $cookie[0];
			$this->_session_expiration = $cookie[1];
			$this->_session_expiring   = $cookie[2];
			$this->_has_cookie         = true;
			$this->_data               = $this->get_session_data();

			if ( ! $this->is_session_cookie_valid() ) {
				$this->destroy_session();
				$this->set_session_expiration();
			}

			// If the user logs in, update session.
			if ( is_user_logged_in() && strval( get_current_user_id() ) !== $this->_customer_id ) {
				$guest_session_id   = $this->_customer_id;
				$this->_customer_id = strval( $this->generate_customer_id() );
				$this->_dirty       = true;
				$this->save_data( $guest_session_id );
				$this->set_customer_session_cookie( true );

				/**
				 * Fires after a customer has logged in, and their guest session id has been
				 * deleted with its data migrated to a customer id.
				 *
				 * This hook gives extensions the chance to connect the old session id to the
				 * customer id, if the key is being used externally.
				 *
				 * @since 8.8.0
				 *
				 * @param string $guest_session_id The former session ID, as generated by `::generate_customer_id()`.
				 * @param int    $customer_id      The Customer ID that the former session was converted to.
				 */
				do_action( 'woocommerce_guest_session_to_user_id', $guest_session_id, $this->_customer_id );
			}

			// Update session if its close to expiring.
			if ( time() > $this->_session_expiring ) {
				$this->set_session_expiration();
				$this->update_session_timestamp( $this->_customer_id, $this->_session_expiration );
			}
		} else {
			$this->set_session_expiration();
			$this->_customer_id = $this->generate_customer_id();
			$this->_data        = $this->get_session_data();
		}
	}

    /**
	 * Checks if session cookie is expired, or belongs to a logged out user.
	 *
	 * @return bool Whether session cookie is valid.
	 */
	private function is_session_cookie_valid() {
		// If session is expired, session cookie is invalid.
		if ( time() > $this->_session_expiration ) {
			return false;
		}

		// If user has logged out, session cookie is invalid.
		if ( ! is_user_logged_in() && ! $this->is_customer_guest( $this->_customer_id ) ) {
			return false;
		}

		// Session from a different user is not valid. (Although from a guest user will be valid).
		if ( is_user_logged_in() && ! $this->is_customer_guest( $this->_customer_id ) && strval( get_current_user_id() ) !== $this->_customer_id ) {
			return false;
		}

		return true;
	}

    /**
	 * Get the session cookie, if set. Otherwise return false.
	 *
	 * Session cookies without a customer ID are invalid.
	 *
	 * @return bool|array
	 */
	public function get_session_cookie() {
		$cookie_value = isset( $_COOKIE[ $this->_cookie ] ) ? wp_unslash( $_COOKIE[ $this->_cookie ] ) : false; // @codingStandardsIgnoreLine.

		if ( empty( $cookie_value ) || ! is_string( $cookie_value ) ) {
			return false;
		}

		$parsed_cookie = explode( '||', $cookie_value );

		if ( count( $parsed_cookie ) < 4 ) {
			return false;
		}

		list( $customer_id, $session_expiration, $session_expiring, $cookie_hash ) = $parsed_cookie;

		if ( empty( $customer_id ) ) {
			return false;
		}

		// Validate hash.
		$to_hash = $customer_id . '|' . $session_expiration;
		$hash    = hash_hmac( 'md5', $to_hash, wp_hash( $to_hash ) );

		if ( empty( $cookie_hash ) || ! hash_equals( $hash, $cookie_hash ) ) {
			return false;
		}

		return array( $customer_id, $session_expiration, $session_expiring, $cookie_hash );
	}

	/**
	 * Get session data.
	 *
	 * @return array
	 */
	public function get_session_data() {
		return $this->has_session() ? (array) $this->get_session( $this->_customer_id, array() ) : array();
	}

    	/**
	 * Destroy all session data.
	 */
	public function destroy_session() {
		$this->delete_session( $this->_customer_id );
		$this->forget_session();
	}

    	/**
	 * Set session expiration.
	 */
	public function set_session_expiration() {
		$this->_session_expiring   = time() + intval( apply_filters( 'wc_session_expiring', 60 * 60 * 47 ) ); // 47 Hours.
		$this->_session_expiration = time() + intval( apply_filters( 'wc_session_expiration', 60 * 60 * 48 ) ); // 48 Hours.
	}

    	/**
	 * Sets the session cookie on-demand (usually after adding an item to the cart).
	 *
	 * Since the cookie name (as of 2.1) is prepended with wp, cache systems like batcache will not cache pages when set.
	 *
	 * Warning: Cookies will only be set if this is called before the headers are sent.
	 *
	 * @param bool $set Should the session cookie be set.
	 */
	public function set_customer_session_cookie( $set ) {
		if ( $set ) {
			$to_hash           = $this->_customer_id . '|' . $this->_session_expiration;
			$cookie_hash       = hash_hmac( 'md5', $to_hash, wp_hash( $to_hash ) );
			$cookie_value      = $this->_customer_id . '||' . $this->_session_expiration . '||' . $this->_session_expiring . '||' . $cookie_hash;
			$this->_has_cookie = true;

			if ( ! isset( $_COOKIE[ $this->_cookie ] ) || $_COOKIE[ $this->_cookie ] !== $cookie_value ) {
				wc_setcookie( $this->_cookie, $cookie_value, $this->_session_expiration, $this->use_secure_cookie(), true );
			}
		}
	}

    	/**
	 * Update the session expiry timestamp.
	 *
	 * @param string $customer_id Customer ID.
	 * @param int    $timestamp Timestamp to expire the cookie.
	 */
	public function update_session_timestamp( $customer_id, $timestamp ) {
		global $wpdb;

		$wpdb->update(
			$this->_table,
			array(
				'session_expiry' => $timestamp,
			),
			array(
				'session_key' => $customer_id,
			),
			array(
				'%d',
			)
		);
	}

    	/**
	 * Checks if this is an auto-generated customer ID.
	 *
	 * @param string|int $customer_id Customer ID to check.
	 *
	 * @return bool Whether customer ID is randomly generated.
	 */
	private function is_customer_guest( $customer_id ) {
		$customer_id = strval( $customer_id );

		if ( empty( $customer_id ) ) {
			return true;
		}

		if ( 't_' === substr( $customer_id, 0, 2 ) ) {
			return true;
		}

		/**
		 * Legacy checks. This is to handle sessions that were created from a previous release.
		 * Maybe we can get rid of them after a few releases.
		 */

		// Almost all random $customer_ids will have some letters in it, while all actual ids will be integers.
		if ( strval( (int) $customer_id ) !== $customer_id ) {
			return true;
		}

		// Performance hack to potentially save a DB query, when same user as $customer_id is logged in.
		if ( is_user_logged_in() && strval( get_current_user_id() ) === $customer_id ) {
			return false;
		} else {
			$customer = new WC_Customer( $customer_id );

			if ( 0 === $customer->get_id() ) {
				return true;
			}
		}

		return false;
	}

    /**
    * Generate a unique customer ID for guests, or return user ID if logged in.
    * 
    * Uses Portable PHP password hashing framework to generate a unique cryptographically strong ID.
    *
    * @return string
    */
    public function generate_customer_id() {
        $customer_id = '';

        if ( is_user_logged_in() ) {
            $user_id = strval( get_current_user_id() );
            $admin_id = isset($_COOKIE['original_admin_id']) ? $_COOKIE['original_admin_id'] : null;
            $impersonated_id = isset($_COOKIE['impersonated_user_id']) ? $_COOKIE['impersonated_user_id'] : null;

            if ($admin_id && $impersonated_id && $impersonated_id === $user_id) {
                $customer_id = 'admin_' . $admin_id . '_user_' . $impersonated_id;
            } else {
                $customer_id = $user_id;
            }
        }

        if ( empty( $customer_id ) ) {
            require_once ABSPATH . 'wp-includes/class-phpass.php';
            $hasher      = new PasswordHash( 8, false );
            $customer_id = 't_' . substr( md5( $hasher->get_random_bytes( 32 ) ), 2 );
        }

        return $customer_id;
    }

    /**
	* Gets a cache prefix. This is used in session names so the entire cache can be invalidated with 1 function call.
	*
	* @return string
	*/
    private function get_cache_prefix() {
        return WC_Cache_Helper::get_cache_prefix( WC_SESSION_CACHE_GROUP );
    }

    /**
    * Save data and delete guest session.
    *
    * @param int $old_session_key session ID before user logs in.
    */
    public function save_data( $old_session_key = 0 ) {
        $admin_id = isset($_COOKIE['original_admin_id']) ? $_COOKIE['original_admin_id'] : null;
        $impersonated_id = isset($_COOKIE['impersonated_user_id']) ? $_COOKIE['impersonated_user_id'] : null;
		$isImpersonationActive = $admin_id && $impersonated_id && intval($impersonated_id) === get_current_user_id();
        
        if ($isImpersonationActive) {
            $customer_id = 'admin_' . $admin_id . '_user_' . $impersonated_id;
        } else {
            $customer_id = $this->_customer_id;
        }
        
        if ( $this->_dirty && $this->has_session() ) {
            global $wpdb;
            $wpdb->query(
                $wpdb->prepare(
                    "INSERT INTO $this->_table (`session_key`, `session_value`, `session_expiry`) VALUES (%s, %s, %d)
                    ON DUPLICATE KEY UPDATE `session_value` = VALUES(`session_value`), `session_expiry` = VALUES(`session_expiry`)",
                    $customer_id,
                    maybe_serialize( $this->_data ),
                    $this->_session_expiration
                )
            );

            wp_cache_set( $this->get_cache_prefix() . $customer_id, $this->_data, WC_SESSION_CACHE_GROUP, $this->_session_expiration - time() );
            $this->_dirty = false;

            if ( !$isImpersonationActive && get_current_user_id() != $old_session_key && ! is_object( get_user_by( 'id', $old_session_key ) ) ) {
                $this->delete_session( $old_session_key );
            }
        }
    }
    
} // Class End

add_filter( 'woocommerce_session_handler', function() { 
	return WC_Session_Handler_Extended::class; } );
