<?php
if (!defined('ABSPATH')) {
    exit; // Exit if accessed directly.
}

use Aws\CloudFront\CloudFrontClient;

/**
 * Handle DXF file download requests securely via AJAX.
 */
add_action('wp_ajax_handle_dxf_download', 'handle_dxf_download_request');
function handle_dxf_download_request() {
    // 1. Security: Check if the user is logged in.
    if (!is_user_logged_in()) {
        wp_die('Access denied. You must be logged in to download files.', 'Access Denied', ['response' => 403]);
    }
    
    $has_architect_access = function_exists('starke_has_architect_access') && starke_has_architect_access();
    $is_impersonating     = function_exists('impersonation_is_active') && impersonation_is_active();

    if ( ! $has_architect_access && ! $is_impersonating ) {
         wp_die('Access denied. You require Architect Access to download DXF files.', 'Access Denied', ['response' => 403]);
    }

    // 2. Security: Validate the nonce.
    $product_id = isset($_GET['product_id']) ? intval($_GET['product_id']) : 0;
    $nonce = isset($_GET['nonce']) ? sanitize_text_field($_GET['nonce']) : '';

    if (!$product_id || !wp_verify_nonce($nonce, 'dxf_download_nonce_' . $product_id)) {
        wp_die('Invalid or expired download link.', 'Security Check Failed', ['response' => 403]);
    }

    // 3. Get Product and File Details
    $product = wc_get_product($product_id);
    if (!$product) {
        wp_die('Product not found.', 'Error', ['response' => 404]);
    }

    $file_name = $product->get_name() . '.dxf';

    // 4. Get the CloudFront URL from WP Offload Media
    $args = [
        'post_type'      => 'attachment',
        'post_status'    => 'inherit',
        'posts_per_page' => 1,
        'meta_query'     => [
            [
                'key'     => '_wp_attached_file',
                'value'   => $file_name,
                'compare' => 'LIKE',
            ],
        ],
    ];

    $query = new WP_Query($args);
    if (!$query->have_posts()) {
        wp_die('DXF file not found for this product.', 'Error', ['response' => 404]);
    }

    $attachment = $query->posts[0];
    
    // This safely gets the CloudFront URL generated by WP Offload Media
    $cloudfront_url = wp_get_attachment_url($attachment->ID);

    if (!$cloudfront_url) {
        wp_die('Download URL could not be generated.', 'File Not Found', ['response' => 404]);
    }

    // Local/staging fallback: the CloudFront signing key only exists on production's
    // EB server (it's a genuinely sensitive credential, not something to share around).
    // Without it, serve the file straight from local disk via its attached file path,
    // which we do have (from the media export). Once we have our own AWS account and
    // CloudFront distribution set up, this should generate its own signed URL against
    // that instead, the same way production does, just with our own key pair.
    $private_key_path = defined( 'STARKE_DXF_PRIVATE_KEY_PATH' )
        ? STARKE_DXF_PRIVATE_KEY_PATH
        : '/var/app/current/.keys/dxf_download_private_key.pem';

    if ( ! file_exists( $private_key_path ) ) {
        $local_file_path = get_attached_file( $attachment->ID );

        // The DB's recorded path and the actual media export were taken at slightly
        // different times, so some files (confirmed with 4303.dxf) have moved since
        // the path was last recorded. Fall back to searching for the filename
        // anywhere under uploads if the exact recorded path is stale.
        if ( ! $local_file_path || ! file_exists( $local_file_path ) ) {
            $upload_dir = wp_upload_dir();
            $found = glob( trailingslashit( $upload_dir['basedir'] ) . '**/*/' . $file_name );
            if ( empty( $found ) ) {
                // glob() with ** isn't recursive in plain PHP without GLOB_BRACE tricks;
                // fall back to a manual recursive search.
                $iterator = new RecursiveIteratorIterator( new RecursiveDirectoryIterator( $upload_dir['basedir'], FilesystemIterator::SKIP_DOTS ) );
                foreach ( $iterator as $file_info ) {
                    if ( $file_info->getFilename() === $file_name ) {
                        $found = [ $file_info->getPathname() ];
                        break;
                    }
                }
            }
            if ( ! empty( $found ) ) {
                $local_file_path = $found[0];
            }
        }

        if ( $local_file_path && file_exists( $local_file_path ) ) {
            nocache_headers();
            header( 'Content-Type: application/dxf' );
            header( 'Content-Disposition: attachment; filename="' . basename( $local_file_path ) . '"' );
            header( 'Content-Length: ' . filesize( $local_file_path ) );
            readfile( $local_file_path );
            exit;
        }
        wp_die( 'DXF file not found on local disk either (no CloudFront signing key configured for this environment).', 'File Not Found', [ 'response' => 404 ] );
    }

    // 5. Generate the CloudFront Signed URL using AWS SDK
    try {
        $cloudFrontClient = new CloudFrontClient([
            'profile' => 'default',
            'version' => '2014-11-06',
            'region'  => 'us-east-1' // Change to your AWS region
        ]);

        // Setup the signature parameters
        $expires = time() + 15; // URL dies in exactly 15 seconds
        $keyPairId = 'K3A5DCXG206IB0'; // Get this from the CloudFront Console Public Key list

        $signedUrl = $cloudFrontClient->getSignedUrl([
            'url'         => $cloudfront_url,
            'expires'     => $expires,
            'private_key' => $private_key_path,
            'key_pair_id' => $keyPairId
        ]);

        // 6. Redirect the user to the secure edge-download URL
        wp_redirect($signedUrl);
        exit;

    } catch (Exception $e) {
        // Log the exact AWS error to WooCommerce > Status > Logs
        if ( function_exists( 'wc_get_logger' ) ) {
            $logger = wc_get_logger();
            $logger->error( 'AWS SDK Error: ' . $e->getMessage(), array( 'source' => 'starke-dxf-security' ) );
        }
        
        // Show the clean error to the user
        wp_die('A secure connection to the file could not be established.', 'Security Error', ['response' => 500]);
    }
}




/**
 * NEW FUNCTION: Redirect guests trying to access DXF attachment pages.
 *
 * This hooks into WordPress's template loading process and checks if a non-logged-in
 * user is trying to view the auto-generated page for a DXF file. If so, it redirects
 * them to the login page.
 */
add_action('template_redirect', 'redirect_dxf_attachment_for_guests');
function redirect_dxf_attachment_for_guests() {
    // Check if we are on an attachment page and the user is not logged in.
    if ( is_attachment() ) {
        global $post; // Get the global post object for the attachment.
        $attachment_url = wp_get_attachment_url( $post->ID );

        // Check if the file extension is 'dxf'.
        if ( pathinfo( $attachment_url, PATHINFO_EXTENSION ) === 'dxf' ) {
            // If it's a DXF and the user is a guest, redirect them to the login page.
            // After login, they will be sent to the site's homepage.
            $login_url = wp_login_url( home_url() );
            wp_redirect( $login_url );
            exit; // Always exit after a redirect.
        }
    }
}





/**
 * ============================================================
 * SECURE CATALOG DOWNLOAD HANDLER
 * ============================================================
 */

// 1. Define your hidden CloudFront URL here (Server-side only)
define( 'STARKE_CATALOG_SECURE_URL', 'https://d260k5w9fy8qjz.cloudfront.net/wp-content/uploads/2026/01/01233758/Current-Edition-Catalog.pdf' );

// 2. Register the Shortcode [starke_catalog_button]
add_shortcode( 'starke_catalog_button', 'starke_render_secure_catalog_btn' );

function starke_render_secure_catalog_btn( $atts ) {
    // Generate a secure nonce (valid for 12-24 hours usually)
    $nonce = wp_create_nonce( 'starke_catalog_download' );
    
    // Create the obfuscated local link
    // It will look like: yoursite.com/?starke_action=download_catalog&_wpnonce=...
    $download_link = add_query_arg( array(
        'starke_action' => 'download_catalog',
        '_wpnonce'      => $nonce,
    ), home_url( '/' ) );

    // Output the button HTML using your "Gold" style
    // Note: We open in a new tab (_blank) to ensure the redirect works smoothly
    ob_start();
    ?>
    <a href="<?php echo esc_url( $download_link ); ?>" class="starke-3d-btn starke-catalog-btn" target="_blank">
        DOWNLOAD PDF CATALOG <i class="fa fa-download" style="margin-left: 10px;"></i>
    </a>
    <?php
    return ob_get_clean();
}

// 3. Listen for the Download Request
add_action( 'template_redirect', 'starke_handle_catalog_download' );

function starke_handle_catalog_download() {
    // Check if the specific query parameter is present
    if ( isset( $_GET['starke_action'] ) && $_GET['starke_action'] === 'download_catalog' ) {
        
        // A. Verify the Nonce (Security Check)
        // If the nonce is invalid or missing, this check fails and we stop.
        if ( ! isset( $_GET['_wpnonce'] ) || ! wp_verify_nonce( $_GET['_wpnonce'], 'starke_catalog_download' ) ) {
            wp_die( 'Security check failed. Please refresh the page and try again.', 'Secure Download Error', array( 'response' => 403 ) );
        }

        // B. If Valid, Redirect to the CloudFront URL
        // The user never sees the CloudFront URL in the HTML source code, only the final redirect.
        wp_redirect( STARKE_CATALOG_SECURE_URL );
        exit;
    }
}